name: Rust アプリケーションのビルド設定

on:
    push:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    # ========== ジョブ ==========
    BUILD APPLICATION:
        # プラットフォーム
        runs-on: ubuntu-latest
        # このビルドジョブのステップを定義しています。
        steps:
            # ========== STEP ==========
          - uses: actions/checkout@v2

            # ========== STEP ==========
          - name: Build
            run: cargo build --verbose

            # ========== STEP ==========
          - name: Run tests
            run: cargo test --verbose
